import { IEvent } from '@nestjs/cqrs';

/**
 * Interface for publishing domain events within a bounded context.
 * Domain events are fine-grained events generated by aggregates when their state changes.
 * Provides an abstraction layer that allows changing the underlying transport mechanism
 * (EventBus, Kafka, RabbitMQ, etc.) without modifying domain logic.
 */
export interface IDomainEventPublisher {
	/**
	 * Publishes domain events from an aggregate's uncommitted events.
	 *
	 * @param events - Array of domain events to publish
	 * @returns Promise that resolves when all events are published
	 */
	publishAll(events: IEvent[]): Promise<void>;
}

/**
 * Dependency injection token for IDomainEventPublisher.
 */
export const DOMAIN_EVENT_PUBLISHER_TOKEN = Symbol('DomainEventPublisher');
