import { Injectable, Logger } from '@nestjs/common';
import { EventBus, IEvent } from '@nestjs/cqrs';

import { IDomainEventPublisher } from '@/shared/domain/interfaces/domain-event-publisher.interface';

/**
 * EventBus implementation of IDomainEventPublisher.
 * Publishes domain events using NestJS CQRS EventBus for in-process event handling.
 * Domain events are fine-grained events generated by aggregates when their state changes.
 */
@Injectable()
export class EventBusDomainEventPublisher implements IDomainEventPublisher {
	private readonly logger = new Logger(EventBusDomainEventPublisher.name);

	constructor(private readonly eventBus: EventBus) {}

	/**
	 * Publishes domain events from an aggregate's uncommitted events.
	 *
	 * @param events - Array of domain events to publish
	 * @returns Promise that resolves when all events are published
	 */
	async publishAll(events: IEvent[]): Promise<void> {
		// 01: Log the events being published
		if (events.length > 0) {
			this.logger.log(
				`Publishing ${events.length} domain event(s) via EventBus`,
			);

			events.forEach((event) => {
				this.logger.debug(
					`Publishing domain event: ${event.constructor.name}`,
				);
			});
		}

		// 02: Publish all events to EventBus
		await this.eventBus.publishAll(events);
	}
}
